name: sightseeker
description: "A Flutter app for discovering nearby attractions"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  location: ^8.0.0
  google_maps_flutter: ^2.1.1
  geolocator: ^14.0.0
  http: ^1.1.0
  provider: ^6.0.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0       # NEW
  get_it: ^8.0.3               # NEW
  cached_network_image: ^3.3.0  # NEW
  flutter_secure_storage: ^9.2.4 # NEW
  latlong2: ^0.9.0              # NEW for LatLng
  intl: ^0.20.2                 # NEW for formatting
  url_launcher: ^6.1.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true               # NEW for flutter_gen

  assets:
    - assets/images/splash.png
    - assets/images/error.png
    - .env                     # NEW - Add the .env file